# 应用名称
server:
  port: 8354
  servlet:
    context-path: /loader

x-mysql:
#  url: jdbc:mysql://localhost:3306/x_reader?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
  url: jdbc:mysql://localhost:6666/x_reader
  username: root
  password: root
spring:
  application:
    name: x-reader-loader
  datasource:
    url: ${x-mysql.url}
    username: ${x-mysql.username}
    password: ${x-mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none